"""Task domain model."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum, auto
from typing import Any
from uuid import UUID, uuid4


class TaskStatus(Enum):
    """Task lifecycle states."""
    PENDING = auto()
    IN_PROGRESS = auto()
    COMPLETED = auto()
    FAILED = auto()
    CANCELLED = auto()
    SKIPPED = auto()


class TaskPriority(Enum):
    """Task priority levels."""
    CRITICAL = 1
    HIGH = 2
    MEDIUM = 3
    LOW = 4
    TRIVIAL = 5


@dataclass
class TaskResult:
    """Result of task execution."""
    success: bool
    data: Any = None
    error: str | None = None
    execution_time_ms: int = 0
    metadata: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "data": self.data,
            "error": self.error,
            "execution_time_ms": self.execution_time_ms,
            "metadata": self.metadata or {},
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskResult:
        return cls(
            success=data["success"],
            data=data.get("data"),
            error=data.get("error"),
            execution_time_ms=data.get("execution_time_ms", 0),
            metadata=data.get("metadata"),
        )


class Task:
    """
    Represents a single unit of work within a goal.

    Tasks are executable steps generated by the planning process.
    """

    def __init__(
        self,
        task_id: UUID | None = None,
        goal_id: UUID | None = None,
        description: str = "",
        priority: TaskPriority = TaskPriority.MEDIUM,
        tool_name: str | None = None,
        tool_parameters: dict[str, Any] | None = None,
        order: int = 0,
        depends_on: list[UUID] | None = None,
    ):
        self._id = task_id or uuid4()
        self._goal_id = goal_id
        self._description = description
        self._priority = priority
        self._tool_name = tool_name
        self._tool_parameters = tool_parameters or {}
        self._order = order
        self._depends_on = depends_on or []
        self._status = TaskStatus.PENDING
        self._result: TaskResult | None = None
        self._created_at = datetime.now(timezone.utc)
        self._started_at: datetime | None = None
        self._completed_at: datetime | None = None
        self._retry_count = 0
        self._max_retries = 3

    # ═══════════════════════════════════════════════════════════════
    # Properties
    # ═══════════════════════════════════════════════════════════════

    @property
    def id(self) -> UUID:
        """Task unique identifier."""
        return self._id

    @property
    def goal_id(self) -> UUID | None:
        """Parent goal ID."""
        return self._goal_id

    @property
    def description(self) -> str:
        """Task description."""
        return self._description

    @property
    def priority(self) -> TaskPriority:
        """Task priority."""
        return self._priority

    @property
    def tool_name(self) -> str | None:
        """Tool to execute for this task."""
        return self._tool_name

    @property
    def tool_parameters(self) -> dict[str, Any]:
        """Parameters for the tool."""
        return self._tool_parameters.copy()

    @property
    def order(self) -> int:
        """Execution order within the goal."""
        return self._order

    @property
    def depends_on(self) -> list[UUID]:
        """List of task IDs this task depends on."""
        return self._depends_on.copy()

    @property
    def status(self) -> TaskStatus:
        """Current task status."""
        return self._status

    @property
    def result(self) -> TaskResult | None:
        """Task execution result."""
        return self._result

    @property
    def created_at(self) -> datetime:
        """Creation timestamp."""
        return self._created_at

    @property
    def started_at(self) -> datetime | None:
        """Start timestamp."""
        return self._started_at

    @property
    def completed_at(self) -> datetime | None:
        """Completion timestamp."""
        return self._completed_at

    @property
    def retry_count(self) -> int:
        """Current retry count."""
        return self._retry_count

    @property
    def can_retry(self) -> bool:
        """Whether task can be retried."""
        return self._retry_count < self._max_retries

    @property
    def is_executable(self) -> bool:
        """Whether task is ready to execute."""
        return self._status == TaskStatus.PENDING

    @property
    def is_terminal(self) -> bool:
        """Whether task has reached terminal state."""
        return self._status in {
            TaskStatus.COMPLETED,
            TaskStatus.FAILED,
            TaskStatus.CANCELLED,
            TaskStatus.SKIPPED,
        }

    @property
    def execution_time_seconds(self) -> float | None:
        """Calculate execution time if task is complete."""
        if self._started_at and self._completed_at:
            return (self._completed_at - self._started_at).total_seconds()
        return None

    # ═══════════════════════════════════════════════════════════════
    # Status Transitions
    # ═══════════════════════════════════════════════════════════════

    def start(self) -> None:
        """Mark task as in progress."""
        if self._status != TaskStatus.PENDING:
            raise ValueError(f"Cannot start task in {self._status.name} state")
        self._status = TaskStatus.IN_PROGRESS
        self._started_at = datetime.now(timezone.utc)

    def complete(self, result: TaskResult) -> None:
        """Mark task as completed with result."""
        if self._status != TaskStatus.IN_PROGRESS:
            raise ValueError(f"Cannot complete task in {self._status.name} state")
        self._status = TaskStatus.COMPLETED if result.success else TaskStatus.FAILED
        self._result = result
        self._completed_at = datetime.now(timezone.utc)

    def fail(self, error: str) -> None:
        """Mark task as failed."""
        self._status = TaskStatus.FAILED
        self._result = TaskResult(success=False, error=error)
        self._completed_at = datetime.now(timezone.utc)

    def cancel(self) -> None:
        """Cancel the task."""
        if self.is_terminal:
            return
        self._status = TaskStatus.CANCELLED
        self._completed_at = datetime.now(timezone.utc)

    def skip(self) -> None:
        """Skip this task."""
        if self._status != TaskStatus.PENDING:
            raise ValueError(f"Cannot skip task in {self._status.name} state")
        self._status = TaskStatus.SKIPPED
        self._completed_at = datetime.now(timezone.utc)

    def retry(self) -> None:
        """Prepare task for retry."""
        if self._status != TaskStatus.FAILED:
            raise ValueError(f"Cannot retry task in {self._status.name} state")
        if not self.can_retry:
            raise ValueError("Maximum retries exceeded")
        self._retry_count += 1
        self._status = TaskStatus.PENDING
        self._result = None
        self._started_at = None
        self._completed_at = None

    # ═══════════════════════════════════════════════════════════════
    # Dependencies
    # ═══════════════════════════════════════════════════════════════

    def add_dependency(self, task_id: UUID) -> None:
        """Add a dependency on another task."""
        if task_id not in self._depends_on:
            self._depends_on.append(task_id)

    def can_execute(self, completed_task_ids: set[UUID]) -> bool:
        """Check if all dependencies are satisfied."""
        return all(dep in completed_task_ids for dep in self._depends_on)

    # ═══════════════════════════════════════════════════════════════
    # Serialization
    # ═══════════════════════════════════════════════════════════════

    def to_dict(self) -> dict[str, Any]:
        """Convert task to dictionary."""
        return {
            "id": str(self._id),
            "goal_id": str(self._goal_id) if self._goal_id else None,
            "description": self._description,
            "tool_name": self._tool_name,
            "tool_parameters": self._tool_parameters,
            "order": self._order,
            "depends_on": [str(d) for d in self._depends_on],
            "status": self._status.name,
            "result": self._result.to_dict() if self._result else None,
            "created_at": self._created_at.isoformat(),
            "started_at": self._started_at.isoformat() if self._started_at else None,
            "completed_at": self._completed_at.isoformat() if self._completed_at else None,
            "retry_count": self._retry_count,
            "max_retries": self._max_retries,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Task:
        """Create task from dictionary."""
        task = cls(
            task_id=UUID(data["id"]),
            goal_id=UUID(data["goal_id"]) if data.get("goal_id") else None,
            description=data["description"],
            tool_name=data.get("tool_name"),
            tool_parameters=data.get("tool_parameters", {}),
            order=data.get("order", 0),
            depends_on=[UUID(d) for d in data.get("depends_on", [])],
        )
        task._status = TaskStatus[data.get("status", "PENDING")]
        task._created_at = datetime.fromisoformat(data["created_at"])
        if data.get("started_at"):
            task._started_at = datetime.fromisoformat(data["started_at"])
        if data.get("completed_at"):
            task._completed_at = datetime.fromisoformat(data["completed_at"])
        if data.get("result"):
            task._result = TaskResult.from_dict(data["result"])
        task._retry_count = data.get("retry_count", 0)
        task._max_retries = data.get("max_retries", 3)
        return task
