"""Capability Generator for Lya Self-Improvement.

Generates new capabilities based on need analysis and validates them.
Pure Python 3.14+ compatible.
"""

from __future__ import annotations

import ast
import hashlib
import json
import re
import subprocess
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from collections.abc import Sequence

from lya.infrastructure.config.logging import get_logger

logger = get_logger(__name__)


@dataclass
class CapabilitySpec:
    """Specification for a new capability."""
    name: str
    description: str
    purpose: str
    parameters: list[dict[str, Any]]
    returns: dict[str, Any]
    example_usage: str
    test_cases: list[dict[str, Any]]
    tags: list[str] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)


@dataclass
class GeneratedCapability:
    """Generated capability with code and metadata."""
    spec: CapabilitySpec
    code: str
    test_code: str
    generated_at: datetime
    version: str = "1.0.0"
    hash: str = ""

    def __post_init__(self) -> None:
        if not self.hash:
            self.hash = hashlib.sha256(self.code.encode()).hexdigest()[:16]


@dataclass
class ValidationResult:
    """Result of capability validation."""
    success: bool
    passed_tests: int = 0
    failed_tests: int = 0
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    execution_time_ms: float = 0.0


class CapabilityGenerator:
    """
    Generates new capabilities for Lya.

    Analyzes usage patterns, identifies missing capabilities,
    and generates Python code to implement them.
    """

    # Templates for code generation
    CAPABILITY_TEMPLATE = '''"""{name} - {description}

Generated by Lya Self-Improvement System
Version: {version}
Generated: {timestamp}
"""

from __future__ import annotations

import asyncio
from typing import Any
from collections.abc import Sequence

{imports}


class {class_name}:
    """{description}"""

    def __init__(self) -> None:
        """Initialize the capability."""
{init_body}

    async def execute(
        self,
{params}
    ) -> dict[str, Any]:
        """
        Execute the capability.

        Args:
{param_docs}

        Returns:
            Dict with success status and result
        """
        try:
{execution_body}
        except Exception as e:
            return {{
                "success": False,
                "error": str(e),
                "capability": "{name}",
            }}


# Convenience function
async def {function_name}({function_params}) -> dict[str, Any]:
    """Quick access to {name} capability."""
    capability = {class_name}()
    return await capability.execute({function_args})
'''

    TEST_TEMPLATE = '''"""Tests for {name} capability."""

import asyncio
import pytest
from {module_name} import {class_name}, {function_name}


class Test{class_name}:
    """Test suite for {class_name}."""

{test_methods}


if __name__ == "__main__":
    asyncio.run(pytest.main([__file__, "-v"]))
'''

    def __init__(self, output_dir: str | Path | None = None) -> None:
        """Initialize generator.

        Args:
            output_dir: Directory to save generated capabilities
        """
        self.output_dir = Path(output_dir) if output_dir else Path("./generated_capabilities")
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def identify_missing_capabilities(
        self,
        usage_patterns: list[dict[str, Any]],
        existing_capabilities: list[str]
    ) -> list[CapabilitySpec]:
        """
        Identify missing capabilities based on usage patterns.

        Args:
            usage_patterns: List of usage attempts and failures
            existing_capabilities: List of existing capability names

        Returns:
            List of capability specs that should be created
        """
        missing: list[CapabilitySpec] = []

        # Analyze patterns for common unmet needs
        for pattern in usage_patterns:
            if pattern.get("resolved"):
                continue

            description = pattern.get("description", "").lower()

            # Pattern matching for common needs
            if "csv" in description and "csv" not in existing_capabilities:
                missing.append(self._create_csv_spec())

            elif "json" in description and "json" not in existing_capabilities:
                missing.append(self._create_json_spec())

            elif "image" in description and "image" not in existing_capabilities:
                missing.append(self._create_image_spec())

            elif "pdf" in description and "pdf" not in existing_capabilities:
                missing.append(self._create_pdf_spec())

            elif "compression" in description or "zip" in description:
                if "compression" not in existing_capabilities:
                    missing.append(self._create_compression_spec())

            elif "database" in description or "sqlite" in description:
                if "database" not in existing_capabilities:
                    missing.append(self._create_database_spec())

        # Remove duplicates
        seen = set()
        unique = []
        for spec in missing:
            if spec.name not in seen:
                seen.add(spec.name)
                unique.append(spec)

        return unique

    def _create_csv_spec(self) -> CapabilitySpec:
        """Create CSV processing capability spec."""
        return CapabilitySpec(
            name="csv_processor",
            description="Read, write, and process CSV files",
            purpose="Handle CSV data operations",
            parameters=[
                {"name": "path", "type": "str", "required": True},
                {"name": "operation", "type": "str", "required": True, "enum": ["read", "write", "append"]},
                {"name": "data", "type": "list[dict]", "required": False},
                {"name": "delimiter", "type": "str", "default": ","},
            ],
            returns={"type": "dict", "success": "bool", "data": "list[dict]"},
            example_usage='csv_processor("data.csv", "read")',
            test_cases=[
                {"path": "test.csv", "operation": "write", "data": [{"a": 1, "b": 2}]},
                {"path": "test.csv", "operation": "read"},
            ],
            tags=["data", "csv", "files"],
        )

    def _create_json_spec(self) -> CapabilitySpec:
        """Create JSON processing capability spec."""
        return CapabilitySpec(
            name="json_processor",
            description="Read, write, and process JSON files",
            purpose="Handle JSON data operations",
            parameters=[
                {"name": "path", "type": "str", "required": True},
                {"name": "operation", "type": "str", "required": True, "enum": ["read", "write", "append"]},
                {"name": "data", "type": "any", "required": False},
                {"name": "indent", "type": "int", "default": 2},
            ],
            returns={"type": "dict", "success": "bool", "data": "any"},
            example_usage='json_processor("data.json", "read")',
            test_cases=[
                {"path": "test.json", "operation": "write", "data": {"key": "value"}},
                {"path": "test.json", "operation": "read"},
            ],
            tags=["data", "json", "files"],
        )

    def _create_image_spec(self) -> CapabilitySpec:
        """Create image processing capability spec."""
        return CapabilitySpec(
            name="image_processor",
            description="Basic image processing operations",
            purpose="Handle image files and transformations",
            parameters=[
                {"name": "path", "type": "str", "required": True},
                {"name": "operation", "type": "str", "required": True, "enum": ["info", "resize", "convert"]},
                {"name": "width", "type": "int", "required": False},
                {"name": "height", "type": "int", "required": False},
                {"name": "format", "type": "str", "required": False, "enum": ["PNG", "JPEG", "WEBP"]},
            ],
            returns={"type": "dict", "success": "bool", "info": "dict"},
            example_usage='image_processor("photo.jpg", "info")',
            test_cases=[
                {"path": "test.jpg", "operation": "info"},
            ],
            tags=["media", "image", "files"],
            dependencies=["Pillow"],
        )

    def _create_pdf_spec(self) -> CapabilitySpec:
        """Create PDF processing capability spec."""
        return CapabilitySpec(
            name="pdf_processor",
            description="Read and process PDF files",
            purpose="Extract text and metadata from PDFs",
            parameters=[
                {"name": "path", "type": "str", "required": True},
                {"name": "operation", "type": "str", "required": True, "enum": ["info", "text", "pages"]},
                {"name": "page", "type": "int", "required": False},
            ],
            returns={"type": "dict", "success": "bool", "text": "str", "pages": "int"},
            example_usage='pdf_processor("doc.pdf", "text")',
            test_cases=[
                {"path": "test.pdf", "operation": "info"},
            ],
            tags=["document", "pdf", "files"],
            dependencies=["PyPDF2"],
        )

    def _create_compression_spec(self) -> CapabilitySpec:
        """Create compression capability spec."""
        return CapabilitySpec(
            name="compression",
            description="Compress and decompress files",
            purpose="Handle ZIP and archive operations",
            parameters=[
                {"name": "path", "type": "str", "required": True},
                {"name": "operation", "type": "str", "required": True, "enum": ["compress", "decompress", "list"]},
                {"name": "output", "type": "str", "required": False},
                {"name": "format", "type": "str", "default": "zip", "enum": ["zip", "tar", "gz"]},
            ],
            returns={"type": "dict", "success": "bool", "files": "list[str]"},
            example_usage='compression("folder", "compress")',
            test_cases=[
                {"path": "test.zip", "operation": "list"},
            ],
            tags=["compression", "archive", "files"],
        )

    def _create_database_spec(self) -> CapabilitySpec:
        """Create database capability spec."""
        return CapabilitySpec(
            name="database",
            description="SQLite database operations",
            purpose="Query and modify SQLite databases",
            parameters=[
                {"name": "path", "type": "str", "required": True},
                {"name": "query", "type": "str", "required": True},
                {"name": "params", "type": "tuple", "required": False},
            ],
            returns={"type": "dict", "success": "bool", "rows": "list[dict]"},
            example_usage='database("data.db", "SELECT * FROM users")',
            test_cases=[
                {"path": ":memory:", "query": "CREATE TABLE test (id INTEGER)"},
            ],
            tags=["database", "sql", "sqlite"],
        )

    def generate_capability(self, spec: CapabilitySpec) -> GeneratedCapability:
        """
        Generate Python code for a capability.

        Args:
            spec: Capability specification

        Returns:
            Generated capability with code and tests
        """
        # Generate imports based on spec
        imports = self._generate_imports(spec)

        # Generate code body
        class_name = self._to_class_name(spec.name)
        function_name = spec.name.replace("_", "_")

        # Generate parameters
        params_str = self._generate_params(spec.parameters)
        param_docs = self._generate_param_docs(spec.parameters)
        execution_body = self._generate_execution_body(spec)
        init_body = self._generate_init_body(spec)

        # Build function signature
        function_params_list = []
        function_args_list = []
        for param in spec.parameters:
            if param.get("required", True):
                function_params_list.append(f"{param['name']}")
                function_args_list.append(f"{param['name']}={param['name']}")
            else:
                default = repr(param.get("default"))
                function_params_list.append(f"{param['name']}={default}")

        function_params = ", ".join(function_params_list)
        function_args = ", ".join(function_args_list)

        # Generate main code
        code = self.CAPABILITY_TEMPLATE.format(
            name=spec.name,
            description=spec.description,
            version="1.0.0",
            timestamp=datetime.now(timezone.utc).isoformat(),
            imports=imports,
            class_name=class_name,
            init_body=init_body,
            params=params_str,
            param_docs=param_docs,
            execution_body=execution_body,
            function_name=function_name,
            function_params=function_params,
            function_args=function_args,
        )

        # Generate tests
        test_code = self._generate_tests(spec, class_name, function_name)

        return GeneratedCapability(
            spec=spec,
            code=code,
            test_code=test_code,
            generated_at=datetime.now(timezone.utc),
        )

    def _generate_imports(self, spec: CapabilitySpec) -> str:
        """Generate import statements."""
        imports = [
            "from dataclasses import dataclass",
            "from pathlib import Path",
            "from typing import Any",
        ]

        # Add specific imports based on tags
        if "csv" in spec.tags:
            imports.append("import csv")
            imports.append("import io")

        if "json" in spec.tags:
            imports.append("import json")

        if "image" in spec.tags:
            imports.append("from PIL import Image")
            imports.append("import io")

        if "pdf" in spec.tags:
            imports.append("import PyPDF2")

        if "compression" in spec.tags or "zip" in spec.tags:
            imports.append("import zipfile")
            imports.append("import tarfile")
            imports.append("import gzip")
            imports.append("import shutil")

        if "database" in spec.tags:
            imports.append("import sqlite3")

        return "\n".join(imports)

    def _generate_params(self, parameters: list[dict[str, Any]]) -> str:
        """Generate method parameters."""
        lines = []
        for param in parameters:
            name = param["name"]
            type_hint = param.get("type", "Any")
            if param.get("required", True):
                lines.append(f"        {name}: {type_hint},")
            else:
                default = repr(param.get("default"))
                lines.append(f"        {name}: {type_hint} = {default},")
        return "\n".join(lines)

    def _generate_param_docs(self, parameters: list[dict[str, Any]]) -> str:
        """Generate parameter documentation."""
        lines = []
        for param in parameters:
            name = param["name"]
            desc = param.get("description", f"The {name} parameter")
            lines.append(f"            {name}: {desc}")
        return "\n".join(lines)

    def _generate_execution_body(self, spec: CapabilitySpec) -> str:
        """Generate execution body based on capability type."""
        if "csv" in spec.name:
            return '''            path = Path(path).expanduser()

            if operation == "read":
                with open(path, "r", newline="") as f:
                    reader = csv.DictReader(f, delimiter=delimiter)
                    rows = list(reader)
                return {"success": True, "data": rows, "count": len(rows)}

            elif operation == "write":
                if not data:
                    return {"success": False, "error": "No data provided"}
                with open(path, "w", newline="") as f:
                    writer = csv.DictWriter(f, fieldnames=data[0].keys(), delimiter=delimiter)
                    writer.writeheader()
                    writer.writerows(data)
                return {"success": True, "path": str(path), "count": len(data)}

            elif operation == "append":
                with open(path, "a", newline="") as f:
                    writer = csv.DictWriter(f, fieldnames=data[0].keys(), delimiter=delimiter)
                    writer.writerows(data)
                return {"success": True, "path": str(path), "count": len(data)}

            else:
                return {"success": False, "error": f"Unknown operation: {operation}"}'''

        elif "json" in spec.name:
            return '''            path = Path(path).expanduser()

            if operation == "read":
                with open(path, "r") as f:
                    data = json.load(f)
                return {"success": True, "data": data}

            elif operation == "write":
                with open(path, "w") as f:
                    json.dump(data, f, indent=indent)
                return {"success": True, "path": str(path)}

            elif operation == "append":
                existing = []
                if path.exists():
                    with open(path, "r") as f:
                        existing = json.load(f)
                    if not isinstance(existing, list):
                        existing = [existing]
                existing.append(data)
                with open(path, "w") as f:
                    json.dump(existing, f, indent=indent)
                return {"success": True, "path": str(path)}

            else:
                return {"success": False, "error": f"Unknown operation: {operation}"}'''

        elif "database" in spec.name:
            return '''            conn = sqlite3.connect(path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()

            try:
                cursor.execute(query, params or ())

                if query.strip().upper().startswith("SELECT"):
                    rows = [dict(row) for row in cursor.fetchall()]
                    return {"success": True, "rows": rows, "count": len(rows)}
                else:
                    conn.commit()
                    return {"success": True, "affected": cursor.rowcount}
            finally:
                conn.close()'''

        elif "compression" in spec.name:
            return '''            path = Path(path).expanduser()

            if operation == "list":
                if format == "zip":
                    with zipfile.ZipFile(path, "r") as z:
                        files = z.namelist()
                    return {"success": True, "files": files, "count": len(files)}
                else:
                    return {"success": False, "error": f"Format not supported: {format}"}

            elif operation == "compress":
                output_path = Path(output) if output else path.with_suffix(".zip")
                if path.is_dir():
                    shutil.make_archive(str(output_path.with_suffix("")), "zip", path)
                else:
                    with zipfile.ZipFile(output_path, "w") as z:
                        z.write(path, path.name)
                return {"success": True, "output": str(output_path)}

            elif operation == "decompress":
                output_dir = Path(output) if output else path.parent
                output_dir.mkdir(parents=True, exist_ok=True)
                with zipfile.ZipFile(path, "r") as z:
                    z.extractall(output_dir)
                return {"success": True, "output": str(output_dir)}

            else:
                return {"success": False, "error": f"Unknown operation: {operation}"}'''

        else:
            return '''            # Generic capability implementation
            return {
                "success": True,
                "message": f"Executed {operation} on {path}",
                "timestamp": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
            }'''

    def _generate_init_body(self, spec: CapabilitySpec) -> str:
        """Generate __init__ body."""
        return "        pass"

    def _generate_tests(self, spec: CapabilitySpec, class_name: str, function_name: str) -> str:
        """Generate test code."""
        test_methods = []

        for i, test_case in enumerate(spec.test_cases):
            params_str = ", ".join(f"{k}={repr(v)}" for k, v in test_case.items())

            test_methods.append(f'''    @pytest.mark.asyncio
    async def test_{i + 1}(self):
        """Test case {i + 1}."""
        result = await {function_name}({params_str})
        assert result["success"] is True''')

        if not test_methods:
            test_methods.append(f'''    @pytest.mark.asyncio
    async def test_basic(self):
        """Basic test."""
        capability = {class_name}()
        result = await capability.execute()
        assert result["success"] is True''')

        module_name = spec.name

        return self.TEST_TEMPLATE.format(
            name=spec.name,
            module_name=module_name,
            class_name=class_name,
            function_name=function_name,
            test_methods="\n\n".join(test_methods),
        )

    def _to_class_name(self, name: str) -> str:
        """Convert snake_case to ClassName."""
        return "".join(word.capitalize() for word in name.split("_"))

    def validate_capability(self, capability: GeneratedCapability) -> ValidationResult:
        """
        Validate generated capability.

        Args:
            capability: Generated capability to validate

        Returns:
            Validation result
        """
        import time

        start_time = time.time()
        errors = []
        warnings = []

        # Syntax check
        try:
            ast.parse(capability.code)
        except SyntaxError as e:
            errors.append(f"Syntax error: {e}")
            return ValidationResult(
                success=False,
                errors=errors,
                execution_time_ms=(time.time() - start_time) * 1000,
            )

        # Test execution
        passed = 0
        failed = 0

        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = Path(tmpdir)

            # Write capability file
            cap_file = tmp_path / f"{capability.spec.name}.py"
            cap_file.write_text(capability.code)

            # Write test file
            test_file = tmp_path / f"test_{capability.spec.name}.py"
            test_file.write_text(capability.test_code)

            # Write conftest
            conftest = tmp_path / "conftest.py"
            conftest.write_text('''import asyncio
import pytest

@pytest.fixture
def event_loop():
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()
''')

            # Run tests
            try:
                result = subprocess.run(
                    [sys.executable, "-m", "pytest", str(test_file), "-v", "--tb=short"],
                    cwd=tmpdir,
                    capture_output=True,
                    text=True,
                    timeout=60,
                )

                # Parse results
                output = result.stdout + result.stderr
                if "passed" in output:
                    # Extract number of passed tests
                    match = re.search(r'(\d+) passed', output)
                    if match:
                        passed = int(match.group(1))

                if "failed" in output:
                    match = re.search(r'(\d+) failed', output)
                    if match:
                        failed = int(match.group(1))

                if result.returncode != 0 and passed == 0:
                    errors.append(f"Tests failed: {output[-500:]}")

            except subprocess.TimeoutExpired:
                errors.append("Test execution timed out")
            except Exception as e:
                errors.append(f"Test execution error: {e}")

        execution_time = (time.time() - start_time) * 1000

        return ValidationResult(
            success=len(errors) == 0 and passed > 0,
            passed_tests=passed,
            failed_tests=failed,
            errors=errors,
            warnings=warnings,
            execution_time_ms=execution_time,
        )

    def save_capability(
        self,
        capability: GeneratedCapability,
        subdirectory: str | None = None
    ) -> Path:
        """
        Save generated capability to disk.

        Args:
            capability: Capability to save
            subdirectory: Optional subdirectory

        Returns:
            Path to saved file
        """
        save_dir = self.output_dir
        if subdirectory:
            save_dir = save_dir / subdirectory
            save_dir.mkdir(parents=True, exist_ok=True)

        # Save main file
        filename = f"{capability.spec.name}.py"
        filepath = save_dir / filename
        filepath.write_text(capability.code)

        # Save test file
        test_filename = f"test_{capability.spec.name}.py"
        test_filepath = save_dir / test_filename
        test_filepath.write_text(capability.test_code)

        # Save metadata
        meta = {
            "name": capability.spec.name,
            "description": capability.spec.description,
            "generated_at": capability.generated_at.isoformat(),
            "version": capability.version,
            "hash": capability.hash,
            "tags": capability.spec.tags,
            "dependencies": capability.spec.dependencies,
        }
        meta_filepath = save_dir / f"{capability.spec.name}_meta.json"
        meta_filepath.write_text(json.dumps(meta, indent=2))

        logger.info(
            "Capability saved",
            name=capability.spec.name,
            path=str(filepath),
        )

        return filepath

    def generate_and_save(
        self,
        spec: CapabilitySpec,
        validate: bool = True
    ) -> tuple[GeneratedCapability, ValidationResult]:
        """
        Generate and optionally validate a capability.

        Args:
            spec: Capability specification
            validate: Whether to validate

        Returns:
            Tuple of capability and validation result
        """
        capability = self.generate_capability(spec)

        validation = ValidationResult(success=False)
        if validate:
            validation = self.validate_capability(capability)

        if not validate or validation.success:
            self.save_capability(capability)

        return capability, validation


# ═══════════════════════════════════════════════════════════════════════
# SELF-IMPROVEMENT LOOP
# ═══════════════════════════════════════════════════════════════════════

class SelfImprovementLoop:
    """
    Main self-improvement loop for Lya.

    Continuously analyzes usage patterns and generates new capabilities.
    """

    def __init__(
        self,
        generator: CapabilityGenerator | None = None,
        check_interval_minutes: int = 5,
    ) -> None:
        """Initialize improvement loop.

        Args:
            generator: Capability generator
            check_interval_minutes: How often to check for improvements
        """
        self.generator = generator or CapabilityGenerator()
        self.check_interval = check_interval_minutes * 60  # Convert to seconds
        self.running = False

    def analyze_and_improve(
        self,
        usage_patterns: list[dict[str, Any]],
        existing_capabilities: list[str]
    ) -> dict[str, Any]:
        """
        Analyze patterns and generate missing capabilities.

        Args:
            usage_patterns: List of usage attempts
            existing_capabilities: Existing capability names

        Returns:
            Results of improvement attempt
        """
        results = {
            "analyzed_at": datetime.now(timezone.utc).isoformat(),
            "missing_found": 0,
            "generated": [],
            "failed": [],
        }

        # Identify missing capabilities
        missing = self.generator.identify_missing_capabilities(
            usage_patterns,
            existing_capabilities,
        )

        results["missing_found"] = len(missing)

        # Generate each capability
        for spec in missing:
            try:
                capability, validation = self.generator.generate_and_save(spec)

                if validation.success:
                    results["generated"].append({
                        "name": spec.name,
                        "path": str(self.generator.output_dir / f"{spec.name}.py"),
                        "validation": validation.__dict__,
                    })
                else:
                    results["failed"].append({
                        "name": spec.name,
                        "reason": validation.errors,
                    })

            except Exception as e:
                results["failed"].append({
                    "name": spec.name,
                    "reason": [str(e)],
                })

        return results


# ═══════════════════════════════════════════════════════════════════════
# EXAMPLE USAGE
# ═══════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    # Example: Generate capabilities
    generator = CapabilityGenerator(output_dir="./lya_capabilities")

    # Example usage patterns
    patterns = [
        {"description": "need to read csv file", "resolved": False},
        {"description": "parse json data", "resolved": False},
        {"description": "compress folder", "resolved": False},
    ]

    existing = ["file_read", "file_write", "execute_command"]

    # Generate
    loop = SelfImprovementLoop(generator)
    results = loop.analyze_and_improve(patterns, existing)

    print(json.dumps(results, indent=2))
